In [1]:
# creating numpy/n-d arrays
import numpy as np 


In [5]:
arr1 = np.array([1,2,3,4,5]) # here list will be converted in to nd array
arr1

array([1, 2, 3, 4, 5])

In [ ]:
type(arr1) # now it's type is nd array as data type

numpy.ndarray

In [8]:
# 2 dimension array
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr10 = np.empty(())
arr10

array(5.e-324)

In [32]:
arr11 = np.random.random((1))
arr11

array([0.08910096])

In [10]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr7= np.arange(5,16,2)
arr7

array([ 5,  7,  9, 11, 13, 15])

In [14]:
arr8 = np.linspace(10,20,10)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [15]:
arr9 = arr8.copy()
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])