In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
#shape
arr1.shape

(5,)

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#shape
arr2.shape

(2, 3)

In [8]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
arr3.shape

(2, 2, 2)

In [10]:
arr3.ndim

3

In [11]:
arr2.ndim

2

In [12]:
arr1.ndim

1

In [16]:
arr1


array([1, 2, 3, 4, 5])

In [17]:
arr1.size

5

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2.size

6

In [20]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
arr3.size

8

In [25]:
arr1.itemsize

8

In [26]:
arr2.itemsize

8

In [27]:
arr3.itemsize

8

In [28]:
arr1.dtype

dtype('int64')

In [29]:
arr2.dtype

dtype('int64')

In [30]:
arr3.dtype

dtype('int64')

In [31]:
#you can convert the data type 
arr3.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [34]:
lista = range(100)
lista

range(0, 100)

In [35]:
arr11 = np.arange(100)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
import sys 

In [ ]:
print(sys.getsizeof(87)*len(lista))

2800


In [38]:
print(arr1.itemsize*arr11.size)

800


In [39]:
import time


In [40]:
x=range(100000)
y=range(10000,200000)
start_time= time.time()

c =[(x+y) for x,y in zip(x,y)]

print(time.time()-start_time)

0.04711270332336426


In [43]:
a = np.arange(100000)
b = np.arange(100000,200000)

start_time =time.time()
c = a+b
print(time.time()-start_time)

0.0004513263702392578
