In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
#shape
arr1.shape

(5,)

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#shape
arr2.shape

(2, 3)

In [8]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
arr3.shape

(2, 2, 2)

In [10]:
arr3.ndim

3

In [11]:
arr2.ndim

2

In [12]:
arr1.ndim

1

In [16]:
arr1


array([1, 2, 3, 4, 5])

In [17]:
arr1.size

5

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2.size

6

In [20]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
arr3.size

8

In [25]:
arr1.itemsize

8

In [26]:
arr2.itemsize

8

In [27]:
arr3.itemsize

8

In [28]:
arr1.dtype

dtype('int64')

In [29]:
arr2.dtype

dtype('int64')

In [30]:
arr3.dtype

dtype('int64')

In [31]:
#you can convert the data type 
arr3.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])