In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [3]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [ ]:
arr1 * arr2 # vector multiplication (vector * vector)

array([ 4, 10, 18, 28, 40, 54])

In [ ]:
arr1*2 # scalar multiplication (vector * scalar)

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr2>3 # in arr2 wherever it is greater than 3 it will give you false here all values are greater than 3 so all are true

array([ True,  True,  True,  True,  True,  True])

In [7]:
arr2>5

array([False, False,  True,  True,  True,  True])

In [8]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [9]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr3.dot(arr4) 

array([[ 28,  31],
       [100, 112]])

In [14]:
arr1.dot(arr2)

np.int64(154)

In [ ]:
arr1.dot(arr3) # it will throw an error because it doesn't match

ValueError: shapes (6,) and (2,3) not aligned: 6 (dim 0) != 2 (dim 0)

In [ ]:
arr4.max() # it will give you max number

np.int64(11)

In [17]:
arr4.min()

np.int64(6)

In [ ]:
arr4.min(axis=0) #here axis is 0 means i want o/p in column wise how many column 2, so o/p is 6,7 # here I am getting minimum of each column 

array([6, 7])

In [ ]:
# if i want row wise then, here I am getting minimum of each row 
arr4.min(axis=1)

array([ 6,  8, 10])

In [ ]:
arr4.sum() # calculae the sum

np.int64(51)

In [21]:
arr4.sum(axis=0) # column wise sum


array([24, 27])

In [23]:
arr4.mean() # mean of the dataset

np.float64(8.5)

In [26]:
arr4.std() # standard deviation for the entire data

np.float64(1.707825127659933)

In [27]:
arr4.sin()

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [28]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [30]:
np.median(arr4)

np.float64(8.5)

In [31]:
np.exp(arr4) # exponent

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])