In [2]:
import numpy as np

In [7]:
#Ravel function : it will bring higher dimensional arrays to lower dimension

arr1 = np.array([[6,7],[8,9],[10,11]])
arr1


array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
# dimension of the above array is 
arr1.ndim # so 2 dimension

2

In [ ]:
arr1.ravel() # here ravel function bring any 3d 4d or 1d arrays in to 1 dimension without any data loss

array([ 6,  7,  8,  9, 10, 11])

In [ ]:
# transpose row->column, column -> row
arr1.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [ ]:
#stacking -> we can combine 2 arrays
arr2 = np.arange(6).reshape(2,3)
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
arr3 = np.arange(12,18).reshape(2,3)
arr3

array([[12, 13, 14],
       [15, 16, 17]])

In [22]:
# inorder to do  stacking we take a matrix of same length
np.hstack((arr2,arr3)) # stacking horizontly

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [25]:
np.vstack((arr2,arr3))  #vertical stacking

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
# splitting
np.hsplit(arr2,3) # horizontal splitting

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [28]:
np.vsplit(arr2,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [3]:
# fancy indexing
arr4 = np.arange(24).reshape(6,4)
arr4


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# 1st , 3rd and 5th row - you can use fancy indexing
arr4[[0,2,4]] # here i am getting all the rows using index numbers 

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])