In [1]:
import numpy as np

In [5]:
arr1 = np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr1

array([[28, 65, 60, 95, 60],
       [52, 41, 89, 29, 75],
       [51, 35,  4, 40, 80],
       [67, 15, 59, 31, 98]], dtype=int32)

In [ ]:
arr1>50 # boolean array

array([[False,  True,  True,  True,  True],
       [ True, False,  True, False,  True],
       [ True, False, False, False,  True],
       [ True, False,  True, False,  True]])

In [7]:
(arr1>50).shape

(4, 5)

In [ ]:
#indexing using boolean arrays / filtering
arr1[arr1>50]

array([65, 60, 95, 60, 52, 89, 75, 51, 80, 67, 59, 98], dtype=int32)

In [ ]:
arr1[(arr1>50) & (arr1 %2 != 0)] #odd numbers

array([65, 95, 89, 75, 51, 67, 59], dtype=int32)

In [ ]:
arr1[(arr1>50) & (arr1 %2 != 0)] =0 #replaces the conditionsatisfied values to 0

In [18]:
arr1

array([[28,  0, 60,  0, 60],
       [52, 41,  0, 29,  0],
       [ 0, 35,  4, 40, 80],
       [ 0, 15,  0, 31, 98]], dtype=int32)