In [1]:
import numpy as np

In [ ]:
np.random.random() # this gives me any random values from 0 to 1, every time i run this it will generate a new value

0.5097876091641268

In [8]:
# if i want to generate same random value all the time then we have to use the function called seed
np.random.seed(1)
np.random.random()

0.417022004702574

In [13]:
# if we want to generate a random value from a given range then 
np.random.uniform(3,10) # here 3 is my starting number and 10 is my ending number, this number changes at each run 

3.646370163381585

In [ ]:
# if we want to generate a random value from a given range of particular length then
np.random.uniform(1,100,10) # here 10 as length of the list

array([19.43976093, 35.21051198, 40.27997995, 54.34285667, 42.50025693,
       68.83673054, 21.24077272, 87.9336262 ,  3.71137173, 67.37628351])

In [ ]:
np.random.uniform(1,100,10).reshape(2,5) # 2d array

array([[42.31317543, 56.31029302, 14.89830692, 20.61204742, 80.2737123 ],
       [96.857896  , 32.02899364, 69.53993895, 87.76252608, 89.56605969]])

In [17]:
#inorder to generate integer values we have to use randint
np.random.randint(1,10)

9

In [ ]:
np.random.randint(1,10,5) # 5 random values

array([9, 4, 9, 8, 4], dtype=int32)

In [20]:
np.random.randint(1,10,15).reshape(3,5)

array([[8, 9, 7, 4, 8],
       [8, 5, 6, 4, 7],
       [9, 1, 3, 8, 8]], dtype=int32)

In [23]:
a = np.random.randint(1,10,6)
a

array([2, 2, 4, 1, 9, 7], dtype=int32)

In [24]:
# if i want to find out max of this array then
np.max(a)

np.int32(9)

In [25]:
np.min(a)

np.int32(1)

In [ ]:
np.argmax(a) # index of max value by argmax function

np.int64(4)

In [30]:
a[np.argmax(a)]

np.int32(9)

In [31]:
np.argmin(a) # index of min value

np.int64(3)

In [ ]:
a[np.argmin(a)] # inorder see the value 

np.int32(1)

In [37]:

# if i want to replace all the odd value = -1 then 
a = np.random.randint(1,10,6)
a

array([2, 8, 9, 5, 1, 2], dtype=int32)

In [39]:
a[a%2==1]=-1
a

array([ 2,  8, -1, -1, -1,  2], dtype=int32)

In [ ]:
# if i want to create another array for the replaced values rather than modifying it in array for that we have to use where
# where(condition,True,False)

a = np.random.randint(1,20,6)
a

array([18, 11, 17,  6, 14, 18], dtype=int32)

In [ ]:
np.where(a%2==1,-1,a) #where returns me anoher array

array([18, -1, -1,  6, 14, 18], dtype=int32)

In [45]:
a

array([18, 11, 17,  6, 14, 18], dtype=int32)

In [46]:
out = np.where(a%2==1,-1,a)
out

array([18, -1, -1,  6, 14, 18], dtype=int32)

In [47]:
a = np.random.randint(1,50,10)
a

array([34, 21, 11, 33, 26, 22, 40, 33, 20, 26], dtype=int32)

In [51]:
np.sort(a)
a

array([11, 20, 21, 22, 26, 26, 33, 33, 34, 40], dtype=int32)

In [52]:
#percentile function
np.percentile(a,25)

np.float64(21.25)

In [ ]:
np.percentile(a,50) # half of the elements in my array wouldbe less than that particular element

np.float64(26.0)

In [57]:
np.percentile(a,99.8)

np.float64(39.891999999999996)